openapi: 3.1.1
info:
  title: Minha API REST
  description: Pratica 10
  version: 0.1.0

servers:
  - url: http://localhost:3000/
    description: Ambiente de Desenvolvimento

tags:
  - name: usuarios

paths:
  /usuarios:
    post:
      summary: Criação de usuário
      tags:
        - usuarios
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - senha
              properties:
                email:
                  type: string
                senha:
                  type: string
      responses:
        '201':
          description: Usuário criado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Usuario'
        '422':
          description: Email ou senha ausentes
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erro'

  /login:
    post:
      summary: Realiza login
      tags:
        - usuarios
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - usuario
                - senha
              properties:
                usuario:
                  type: string
                senha:
                  type: string
      responses:
        '200':
          description: Login bem sucedido. Retorna token JWT.
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '401':
          description: Credenciais inválidas
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erro'

  /usuarios/renovar:
    post:
      summary: Renovar token JWT
      tags:
        - usuarios
      security:
        - JWTAuth: []
      responses:
        '200':
          description: Token renovado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'
        '401':
          description: Token inválido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mensagem'

  /usuarios/{id}:
    delete:
      summary: Remover usuário
      tags:
        - usuarios
      security:
        - JWTAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Usuário removido com sucesso

components:
  schemas:
    Usuario:
      type: object
      properties:
        id:
          type: string
        email:
          type: string
        senha:
          type: string

    Erro:
      type: object
      properties:
        msg:
          type: string

    Mensagem:
      type: object
      properties:
        msg:
          type: string

  securitySchemes:
    JWTAuth:
      type: apiKey
      in: header
      name: authorization
